name: xKit
main: com.mengcraft.xkit.KitPlugin
version: ${project.version}

commands:
  xkit:
    description: None.
    permission: xkit.use

permissions:
  xkit.admin:
    description: None.
    default: op
  xkit.use:
    description: None.
    default: true

depend: [ProtocolLib, UltraCore]
softdepend: [PlaceholderAPI]
